version: "1.1"

listeners:
  - port: "2222"
    type: ssh
  - port: "8080"
    type: http
  - port: "4343"
    type: http
    ssl: true
  - port: "9000"
    type: tcp

ssh:
  logUsername: true
  logPassword: true
  sshShowedVersion: "SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6"

https:
  serverCertificate: ".dev/server.crt"
  serverCertificateKey: ".dev/server.key"

syslog:
  enabled: false
  server: "127.0.0.1"
  port: "514"
  cliEnabled: true
